name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file alpine --tag my-image-name:$(date +%s)

    - name: Login to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: mariocastronovo/mytest
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: alpine
